### ISSUE TITLE
States preserve old value 

### ISSUE THREAD

**Issue by peer69** [Jey-Cee/ioBroker.deconz#12]
I use deconz gateway v2.0.5.28 and have a xiaomi motion sensor connected to the gateway. 
The motion sensor works as expected, when motion is detected, states in deconz and iobroker are updated accordingly. Unfortunately this isnt the case for lightlevel and lux which the sensor provides. The value is updated in deconz, but the update isnt reflected in iobroker. 

As you can see by the timestamp, the state for presence is updated while the lux state is not. I have testes this with a longer timeframe than just a few minutes, the state hasnt changed over 24 hours with significant changes in deconz for lux value. These screenshots are just from my last test before opening this issue. 

https://pasteboard.co/Hosrz1P.png
https://pasteboard.co/HosuWaM.png

Is there any way to update all states, when an update in deconz occurs?

**Comment by Jey-Cee** [comment]
This issue is a result of using Phoscon APP to teach-in Xiaomi devices. These Devices are recognized normaly as more than one device, but Phoscon APP handle it as one Device. The rest API gives me the single devices so it is not easy to handle this without breaking changes in the Adapter. 

The easy Solution don't use Phoscon APP and use instead the Adapter to teach-in your devices.

**Comment by peer69** [comment]
Thanks! This seems to work now. By adding the sensor through the adapter I end up having two new objects, Presense 17 and LightLevel 10. Any chance I could rename those objects? Tried to but names are being reset to their previous value every time the states are updated.

**Comment by Jey-Cee** [comment]
I will try to change this behaivior.

**Comment by peer69** [comment]
Great! Thank you for your work!
