### ISSUE TITLE
Sensor names are not updated

### ISSUE THREAD

**Issue by zaunermax** [Jey-Cee/ioBroker.deconz#123]
version 1.3.1
deConz version: 2.5.75 - API Version 1.16.0

It seems, that the adapter does not update/fetch the sensor names. I tried to look up similar issues, but i couldn't find anything.

I am mainly using the deconz system for sensors and i have quite a few of them. It is really hard to tell them apart, as the sensors just get listed via numbers in them even if i update the name in the deconz software.

If you point me to the right direction, I might even open a PR myself. Thanks for maintaining this great adapter! (German is also possible but for the sake of other people finding this i decided to write everything in english)

**Comment by Jey-Cee** [comment]
Thats not really a easy thing, because if you are change the name within ioBroker it is never synced to phoscon actually. So all names will be overwritten with the names from phoscon.

That may not be a problem for you but could and would be for others, so i will leave this for now as it is.

If you wish to change this for your self look at main.js line 1213 or 1324 (depends on version) look for `setObjectNotExists` and change it to `setObject`
This will overwrite the whole object at each adapter start.

**Comment by EdgarM73** [comment]
Same for me.

I just started today with deconz, and have added my aqara sensors and named them in the phoscon admin gui.

My light bulbs ars named in iobroker as well, but my sensors all are not .

any update?

**Comment by Jey-Cee** [comment]
Found a solution. Feature will come with version 2.

**Comment by xadox-1st** [comment]
Since v2 development seems to be stopped. Will there be a fix in v1?
If I rename objects in phoscon they should be shown with that name in iobroker, too.
