### ISSUE TITLE
Battery status

### ISSUE THREAD

**Issue by igitlin** [Jey-Cee/ioBroker.deconz#19]
Please add battery status for battery operated device.

**Comment by Jey-Cee** [comment]
Cant do what is already done. 
If there are no battery states on your side please provide some information:
-deConz Version
-Adapter version
-Name and/or model of your devices

**Comment by eumats** [comment]
I have the same problem.
-deConz Version: V2.05.49
-Adapter version: 0.2.5
-Name and/or model of your devices: Xiaomi Door Sensor (not Aquara)

**Comment by Jey-Cee** [comment]
Next Question: Is there a Object for Battery state?

My Aqara switch reports its battery state. It looks like your Xiaomi Door Sensor is already implemented, so it should report its battery state too.

You can check that by changing the loglevel for the deconz instance to debug. 
Then you can see wich data telegrams are send by deconz to ioBroker. 
Looks like these: `Websocket message: {"config":{"battery":100,"group":"4812","on":true,"reachable":true},"e":"changed","id":"3","r":"sensors","t":"event"}`

**Comment by eumats** [comment]
Is there a Object for Battery state?: yes
--> deconz.0.Sensor_37.battery

But the value ist null

Debug Output:
Websocket message: {"e":"added","id":"2","r":"sensors","sensor":{"config":{"battery":null,"on":true,"reachable":true,"temperature":null},"ep":1,"etag":"4d95d8f10e7d09ebadaa96813d573722","id":"2","man

Update: deConz Version updated to V2.05.50. But the problem is still there...

**Comment by Jey-Cee** [comment]
OK Problem seems to be at deConz because its delivering null instead a value.
