### ISSUE TITLE
No API Key

### ISSUE THREAD

**Issue by moonGbox** [Jey-Cee/ioBroker.deconz#221]
Hi everybody,
I have installed the Deconz adapter, but I don't get a connection. With "Hue Essentials" I was able to get a API key, but with the same IP and Port in ioBroker it doesn't work.

deconz.0	2021-02-16 18:53:14.078	error	(1075) Could not connect to deConz/Phoscon. Error: connect EHOSTUNREACH 192.168.0.3:8081
deconz.0	2021-02-16 18:53:02.411	error	(1075) Could not connect to deConz/Phoscon. Error: connect EHOSTUNREACH 192.168.0.3:8081
deconz.0	2021-02-16 18:51:08.000	warn	(1075) No API Key found
deconz.0	2021-02-16 18:51:07.941	info	(1075) starting. Version 1.3.11 in /opt/iobroker/node_modules/iobroker.deconz, node: v12.20.2, js-controller: 3.2.16
host.iobroker	2021-02-16 18:51:05.491	info	instance system.adapter.deconz.0 started with pid 1075
host.iobroker	2021-02-16 18:51:03.489	info	instance system.adapter.deconz.0 terminated with code null 

Does anybody have an idea?

**Comment by Jey-Cee** [comment]
> 8081

Normal the port of deconz is 80 or 8080. So i think you do not use the right port.

**Comment by moonGbox** [comment]
> > 8081
> 
> Normal the port of deconz is 80 or 8080. So i think you do not use the right port.

I've changed the port to 8081 before. To check I've changed it back to 8080, but same problem. I think it doesn't have something to do with the port, because as I mentioned it is working with other third party apps like Hue essentials without any problems. Could it have something to do with the versions of node.js etc? I think, I was reading something like this but didn't found a solution...

**Comment by Jey-Cee** [comment]
The error message is clear, the adapter can not connect to the deconz. Which means there is a network (configuration) problem or a firewall that blocks the connection.

**Comment by adgo** [comment]
Hi @Jey-Cee  I'm expiring the "same" issue
I'm not able to get an Api key via ioBroker frontend deconz adapter configuration with version 1.3.11 
If I'm trying it the manual way <deconzIP>/api  {"devicetype":"name"} -> I recieve a valid response with a api key 
also if I try to ad this key manually the error is the same 
`

  |   |   |  
-- | -- | -- | --
deconz.0 | 2021-03-15 21:39:03.975 | debug | (3312) Websocket connection closed
deconz.0 | 2021-03-15 21:39:03.971 | warn | (3312) Could not connect to websocket instance of deConz/Phoscon. Error: connect EHOSTUNREACH 192.168.2.2:443
deconz.0 | 2021-03-15 21:39:03.968 | error | (3312) Could not connect to deConz/Phoscon. Error: connect EHOSTUNREACH 192.168.2.2:80
deconz.0 | 2021-03-15 21:39:00.791 | info | (3312) starting. Version 1.3.11 in /opt/iobroker/node_modules/iobroker.deconz, node: v12.21.0, js-controller: 3.2.16



`
the deconz service is runing on port 80 and port 80 is set up in the adapter configuration - I also tried without "80" because 80 is quite default but it didn't help 

It worked before - a power unplug of the Raspberry Pi destroyed everything ;-)  NO but so I assume its not a network communication related issue only layer 8 :-)

Best regards 
André

**Comment by Jey-Cee** [comment]
Hi @adgo,
without more information it is impossible for me to help here. As i said before, normal this is not a problem with the adapter.
If you still expirience this problem we can do a remote session and i will have a look on your setup. 
Otherwise please describe how you solved this problem.

Greets 
Jey Cee

**Comment by adgo** [comment]
Thanks for your offer - in the meantime I found out that the reboot killed a network bridge between host and docker so there was really no network communication - so this is no software issue - as I already supposed - layer-8 
thanks 
BR André

**Comment by Jey-Cee** [comment]
Thanks for your reply
