### ISSUE TITLE
Trying to learn from your code

### ISSUE THREAD

**Issue by stefaanv** [Jey-Cee/ioBroker.deconz#318]
Hi,

I'm learning how to create a ioBroker interface and looking into your code because I will also use the deconz interface in my project.  However, I have some problems understanding
- After cloning the repo and doing `npm install` I have 119 errors in the code.  Mostly related to the problem that there is no `Adapter` class in the '@iobroker/adapter-core' module.
- I suspect the deconz adapter transpiled from typescript ?  If so, where can I find the typescript code ?  

Kind Regards

**Comment by Jey-Cee** [comment]
Do not use this code as reference, because it is not using the latest adapter base. 
Create a new adapter with adapter creator: https://github.com/ioBroker/create-adapter#readme
Also it is using the deprecated request package, which should not be used in new projects.

I have no clue why you are getting this errors. Do you get this errors in your IDE or if you try to running the adapter?

This adapter is js only, no typescript.

**Comment by stefaanv** [comment]
OK, thanks, I'll have a look there.
