### ISSUE TITLE
Manufacturer, Name, FW-Version as State

### ISSUE THREAD

**Issue by LoPablo** [Jey-Cee/ioBroker.deconz#39]
Would it be possible to add the Manufacturer (Ikea, Philipps, Osram..), the Model (ColorBulb, ColorStrip...)the Name of the device and for example the Firmware-Version of the device as a State so it can be used for displaying the device correctly with a AccessoryInformation Service in Yahka?

**Comment by Jey-Cee** [comment]
It is possible but not necessary, because this information is already available. See screenshot.
![image](https://user-images.githubusercontent.com/16007760/55146314-9e7b0880-5144-11e9-97be-760b70522b01.png)

If you need it explicit as states, add it manual or contact developer of yhaka adapter to read this information from the natives.

**Comment by LoPablo** [comment]
Oh, I didn't even know this view existed my bad. I will have to take a closer look at if Yahka maybe has a function for nativ values. Thank you very much.
