### ISSUE TITLE
First experience

### ISSUE THREAD

**Issue by daniel-lo** [Jey-Cee/ioBroker.deconz#78]
Hi, I just converted from CC zigbee stick to conbee. What strikes me is that the states are really unclear. For example the Aqara Cube appears twice and neither the state names nore the states themselves are self-explanatory. What are these values that represent the rotation angle and why is it a buttonevent? How is a doubletap represented in the object list?

I will manage (somehow) .. but it would be fantastic to habe better a match between the zigbee adapter and the deconz adapter to make transitions easier. Zigbee-adapter wins in user-friendlyness.

Last but not least I miss some kind of information about signal strenght.

I'm not complaining .. just giving feedback. I am thankful that this adapter exists.

**Comment by Jey-Cee** [comment]
Thank you for your feedback. 
You can not compare the Zigbee adapter and the deConz adapter, because the Zigbee adapter is based on a open source project that is written by ioBroker developers. 
deConz is a stand alone solution that provides an API, wich i using. The adapter do not interpret any device specific data, because it is a lot work to do and needs a lot of information. 
The adapter provides only the API as ioBroker object structure.

I do not know whats the values for the Cube are. But have a look at the german ioBroker forum, there was a lot of discussion about the cube and deConz.

The cube appears twice as they is delivered as two seperate sensors, thats how deConz handle this devices.

Signal strength isnt delivered by deConz.

**Comment by daniel-lo** [comment]
Thank you for following-up!

**Comment by daniel-lo** [comment]
Is there any simple way to get the decimal point into the rotation angle? Cheers
