### ISSUE TITLE
deCONZ getting killed over and over again

### ISSUE THREAD

**Issue by mobilutz** [Jey-Cee/ioBroker.deconz#92]
It seems, that version 1.2.1 keeps getting killed by ioBroker directly.

My host logs show something like this:
```
deconz.0 | 2020-01-09 21:14:53.740 | info | (726) Got terminate signal TERMINATE_YOURSELF
host.pi | 2020-01-09 21:14:53.642 | info | stopInstance system.adapter.deconz.0 send kill signal
host.pi | 2020-01-09 21:14:53.641 | info | stopInstance system.adapter.deconz.0 (force=false, process=true)
deconz.0 | 2020-01-09 21:14:53.469 | info | (726) Auto discovery
deconz.0 | 2020-01-09 21:14:53.428 | info | (726) starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.deconz, node: v10.15.2
host.pi | 2020-01-09 21:14:49.157 | info | instance system.adapter.deconz.0 started with pid 726
```

I tried looking into this already, but didn't find anything yet 😦 

Can you maybe help me?
Thanks

**Comment by mobilutz** [comment]
Now, I see this in the logs:
```
host.pi | 2020-01-09 21:42:42.007 | info | instance system.adapter.deconz.0 terminated with code 156 (156)
```

I did find, that this code `156` was problematic on other adapters as well, but I don't know why deconz is only problematic for me.

**Comment by Jey-Cee** [comment]
This is a generell problem of this version for all users. You have to go back to an earlier version. The error code does not tell the truth, it is just random. 
I know the problem and will fix it soon. 
If you need stable version please use the default repo of ioBroker.

**Comment by mobilutz** [comment]
> I know the problem and will fix it soon.

Thanks for the fast reply. Is there anything I can help with?
I am a JS developer and could open a PR for that.
(But I guess it is just faster when you do it)

**Comment by Jey-Cee** [comment]
Should be working now. Delete Adapter and install the new version.

**Comment by mobilutz** [comment]
Thanks, now this error does not happen. But I stumble over another problem :(
https://github.com/iobroker-community-adapters/ioBroker.deconz/issues/94

**Comment by Stefan-83** [comment]
Hi,
i just installed the current version of deCONZ adapter (1.3.10) and have the same issue (restarting every 30 seconds).

`
host.ioBrokerGarage | 2020-09-03 12:05:43.651 | info | Restart adapter system.adapter.deconz.0 because enabled
-- | -- | -- | --
host.ioBrokerGarage | 2020-09-03 12:05:43.649 | error | instance system.adapter.deconz.0 terminated with code 156 (156)
deconz.0 | 2020-09-03 12:05:43.064 | warn | (5815) Got terminate signal. Checking desired PID: 5846 vs own PID 5815
deconz.0 | 2020-09-03 12:05:43.051 | debug | (5815) Websocket connection closed
deconz.0 | 2020-09-03 12:05:43.045 | info | (5815) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
deconz.0 | 2020-09-03 12:05:43.040 | info | (5815) terminating
deconz.0 | 2020-09-03 12:05:43.037 | info | (5815) cleaned everything up...
deconz.0 | 2020-09-03 12:05:43.032 | warn | (5815) Got terminate signal. Checking desired PID: 0 vs own PID 5815
host.ioBrokerGarage | 2020-09-03 12:05:43.022 | info | instance system.adapter.deconz.0 started with pid 5846
`
